# **Anomoly Detection**

In [44]:
from tensorflow.keras.layers import Dense,Activation,BatchNormalization,Dropout,Input

In [45]:
import numpy as np
import tensorflow as tf

In [46]:
input_size = (100000,10)

In [47]:
normal_data = np.random.normal(loc=5,scale=1,size=input_size)
normal_data.shape

(100000, 10)

In [48]:
normal_data

array([[4.4983796 , 3.9669054 , 5.38689957, ..., 5.15901501, 3.81173196,
        5.00606152],
       [5.16270277, 5.43053968, 5.43370331, ..., 5.48112304, 4.39256271,
        3.45400493],
       [5.87354598, 5.27835172, 5.75469613, ..., 3.69931525, 3.75644507,
        6.40878723],
       ...,
       [4.83550401, 4.17121389, 5.71932203, ..., 3.77619908, 5.20382806,
        2.88510112],
       [3.92507071, 6.71592775, 6.50250481, ..., 5.58766552, 6.69160654,
        5.90694601],
       [5.10177108, 5.3972515 , 3.44853533, ..., 7.42854615, 4.4949199 ,
        5.58062445]])

In [49]:
normalize_data = (normal_data - np.min(normal_data)) / (np.max(normal_data) - np.min(normal_data))

In [50]:
autoencoder = tf.keras.Sequential([
    Input(shape=(input_size[1],)),
    BatchNormalization(),
    Dense(units=64),
    BatchNormalization(),
    Activation('relu'),
    Dropout(0.2),
    Dense(units=32),
    BatchNormalization(),
    Activation('relu'),
    Dense(units=16),
    BatchNormalization(),
    Activation('relu'),
    Dense(units=input_size[1],),
    Activation('sigmoid')
])

In [51]:
autoencoder.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [52]:
autoencoder.fit(normalize_data,normalize_data,epochs=20,batch_size=32,validation_split=0.2)

Epoch 1/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.0070 - mse: 0.0070 - val_loss: 6.1057e-04 - val_mse: 6.1057e-04
Epoch 2/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0017 - mse: 0.0017 - val_loss: 3.2766e-04 - val_mse: 3.2766e-04
Epoch 3/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0015 - mse: 0.0015 - val_loss: 2.3096e-04 - val_mse: 2.3096e-04
Epoch 4/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0014 - mse: 0.0014 - val_loss: 2.0493e-04 - val_mse: 2.0493e-04
Epoch 5/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 0.0013 - mse: 0.0013 - val_loss: 2.0797e-04 - val_mse: 2.0797e-04
Epoch 6/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 0.0012 - mse: 0.0012 - val_loss: 1.8437e-04 - val_mse: 1.8437e-04
Epoch 7/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.0012 - mse: 0.0012 - val_loss: 1.5885e-04 - val_mse: 1.5885e-04
Epoch 8/20
2500/2500 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.0012 - mse: 0.0012 - val_loss: 1.5066e-0

In [53]:
np.array([100,200,300])

array([100, 200, 300])

In [54]:
abnormal_data = np.array([[10,270,30,50,60,90,0,99,10,29]])

In [55]:
normalize_abnormal_data = (abnormal_data - np.min(abnormal_data)) / np.max(abnormal_data) - np.min(abnormal_data) 

In [56]:
normalize_abnormal_data

array([[0.03703704, 1.        , 0.11111111, 0.18518519, 0.22222222,
        0.33333333, 0.        , 0.36666667, 0.03703704, 0.10740741]])

In [57]:
normalize_data[0]

array([0.47597292, 0.42165736, 0.56677781, 0.62143893, 0.47438319,
       0.42876575, 0.38460164, 0.54348848, 0.40579896, 0.52785695])

In [58]:
test_normal = autoencoder.predict(np.array([normalize_data[1]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step


In [59]:
test_anomoly = autoencoder.predict(normalize_abnormal_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


In [60]:
np.sum(abs(test_normal - np.array([normalize_data[1]])))

0.06479357974284095

In [61]:
np.sum(abs(test_anomoly - normalize_abnormal_data))

1.13205943107605